spring.application.name=examen
basePath=/tecnico/examen
tvmaze.api.url=https://api.tvmaze.com
spring.data.mongodb.uri=mongodb+srv://arezto20_db_user:gEJmuv0vbLonOcMy@cluster0.zfb8vtc.mongodb.net/sample_mflix?retryWrites=true&w=majority